version: '3.2'
services:
  kafka1:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - 19092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_zoo1:2181,zookeeper_zoo2:2181,zookeeper_zoo3:2181/kafka-2.2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_HOST_IP:19092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    networks:
      - gateway
    volumes:
      - kafka1:/kafka
  kafka2:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - 29092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_zoo1:2181,zookeeper_zoo2:2181,zookeeper_zoo3:2181/kafka-2.2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_HOST_IP:29092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    networks:
      - gateway
    volumes:
      - kafka2:/kafka
  kafka3:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - 39092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_zoo1:2181,zookeeper_zoo2:2181,zookeeper_zoo3:2181/kafka-2.2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_HOST_IP:39092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    networks:
      - gateway
    volumes:
      - kafka3:/kafka

networks:
  gateway:
    external: true

volumes:
  kafka1:
  kafka2:
  kafka3:

